### ISSUE TITLE
cant build local fork

### ISSUE THREAD

**Issue by Corallus-Caninus** [sidju/add-ed#5]
in hired, trying to reference a local clone of add-ed results in there being no feature named vecbuffer.

steps to reproduce error:
1. clone hired
2. clone add-ed
3. set add-ed in hired's Cargo.toml to local add-ed e.g.: path="../add-ed"
4. cargo build

I tried removing the feature from hired in Cargo.toml and explicitly setting it in add-ed but still cant find VecBuffer in hired. patch notes suggest feature is implicit but it cannot be found when removing the feature flag despite versioning being the same in remote and local add-ed.

**Comment by sidju** [comment]
It is because you are connecting them directly when their main branches are out of sync. Try it after checking out the tag for the add-ed version used by hired.

I have refactored add-ed to add the last features and am improving the testing (slowly, in the tmp branch) before I make a release of it.

If you'd like you can update your fork of hired to work with the latest add-ed, it should just be to:
- use Buffer instead of VecBuffer (same code, but now as an object instead of a trait implementor)
- construct LocalIO (handles shell escape and file interactions) in the same way as Buffer and handing it into the Ed constructor
- add the lock_ui and unlock_ui funtions to hired's UI, see ClassicUI's implementations in add-ed. (they don't need to do anything special, but it would be nice it they printed exclamation mark on their own line to match GNU Ed's behaviour)

If you do you are welcome to make a PR that I can merge when I have made the add-ed release.

-------- Original Message --------

**Comment by Corallus-Caninus** [comment]
I believe the binary didn't get updated when crates.io was updated.

a workspace may help with dependency issues.

https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html

**Comment by sidju** [comment]
add-ed and hired are intentionally out of sync, since I am still verifying the functionality on add-ed after a major refactor and don't wish to prioritize updating hired to use the new API before I am sure add-ed is functional. This isn't a mistake, it is a choice that enables the master branches of both add-ed and hired to build during this API change.

I know of cargo workspaces and have used them before, but my intent isn't to couple hired that tightly to add-ed.
